labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the feature or enhancement. What is it? How would it work?"
